# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: cacappmodacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build docker image
        run: |     
          docker build -t cacappmodacr.azurecr.io/wcftest:${{ github.sha }} ./TestWcfService
          docker push cacappmodacr.azurecr.io/wcftest:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'cac-appmod-wcftest'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'cacappmodacr.azurecr.io/wcftest:${{ github.sha }}'
